disabled_rules:
  - colon
  - comma
  - control_statement
  - multiple_closures_with_trailing_closure
opt_in_rules:
  - empty_count

included:
  - Source
excluded:
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift
analyzer_rules:
  - explicit_self

force_cast: warning
force_try:
  severity: error

line_length: 300
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 1000
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: ["_"]
identifier_name:
  min_length:
    error: 4
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
